[package]
name = "siirs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.2"
anyhow = "1.0.70"
byteorder = "1.4.3"
cbc = "0.1.2"
compress = {version = "0.2.1", features = ["zlib"]}
